import csv
import os

# id,lemma,pos,level,zh_meaning,en_meaning,example_fr,example_zh,example_en
# pos: nm (noun masc), nf (noun fem), v (verb), adj (adjective), adv (adverb), conj (conjunction), prep (preposition), pron (pronoun)

words_data = [
    (1, "bonjour", "nm", "A1", "你好", "hello", "Bonjour, comment allez-vous ?", "你好，您怎么样？", "Hello, how are you?"),
    (2, "merci", "nm", "A1", "谢谢", "thank you", "Merci beaucoup !", "非常感谢！", "Thank you very much!"),
    (3, "maison", "nf", "A1", "房子", "house", "La maison est grande.", "房子很大。", "The house is big."),
    (4, "manger", "v", "A1", "吃", "to eat", "Nous mangeons à midi.", "我们中午吃饭。", "We eat at noon."),
    (5, "chien", "nm", "A1", "狗", "dog", "Le chien aboie.", "狗在叫。", "The dog barks."),
    (6, "chat", "nm", "A1", "猫", "cat", "Le chat dort sur le canapé.", "猫在沙发上睡觉。", "The cat sleeps on the sofa."),
    (7, "eau", "nf", "A1", "水", "water", "Je bois de l'eau.", "我喝水。", "I drink water."),
    (8, "livre", "nm", "A1", "书", "book", "Je lis un livre intéressant.", "我在读一本有趣的书。", "I am reading an interesting book."),
    (9, "fille", "nf", "A1", "女孩", "girl", "La fille joue dans le parc.", "女孩在公园里玩。", "The girl is playing in the park."),
    (10, "garçon", "nm", "A1", "男孩", "boy", "Le garçon court vite.", "男孩跑得快。", "The boy runs fast."),
    (11, "femme", "nf", "A1", "女人；妻子", "woman; wife", "Cette femme est mon professeur.", "这位女士是我的老师。", "This woman is my teacher."),
    (12, "homme", "nm", "A1", "男人", "man", "Un homme marche dans la rue.", "一个男人走在街上。", "A man walks in the street."),
    (13, "école", "nf", "A1", "学校", "school", "Les enfants vont à l'école.", "孩子们去上学。", "The children go to school."),
    (14, "travailler", "v", "A1", "工作", "to work", "Il travaille tous les jours.", "他每天工作。", "He works every day."),
    (15, "parler", "v", "A1", "说话", "to speak", "Elle parle français.", "她会说法语。", "She speaks French."),
    (16, "aimer", "v", "A1", "爱；喜欢", "to love; to like", "J'aime la musique.", "我喜欢音乐。", "I like music."),
    (17, "regarder", "v", "A1", "看", "to look at; to watch", "Nous regardons un film.", "我们在看一部电影。", "We are watching a movie."),
    (18, "écouter", "v", "A1", "听", "to listen", "Écoutez-moi bien.", "好好听我说。", "Listen to me carefully."),
    (19, "aller", "v", "A1", "去", "to go", "Je vais à la gare.", "我去火车站。", "I go to the train station."),
    (20, "venir", "v", "A1", "来", "to come", "Viens avec moi !", "跟我一起来！", "Come with me!"),
    (21, "faire", "v", "A1", "做", "to do; to make", "Qu'est-ce que tu fais ?", "你在做什么？", "What are you doing?"),
    (22, "être", "v", "A1", "是", "to be", "Je suis étudiant.", "我是学生。", "I am a student."),
    (23, "avoir", "v", "A1", "有", "to have", "J'ai un chien.", "我有一只狗。", "I have a dog."),
    (24, "grand", "adj", "A1", "大的", "big; tall", "Cet arbre est très grand.", "这棵树很大。", "This tree is very tall."),
    (25, "petit", "adj", "A1", "小的", "small; short", "Mon frère est encore petit.", "我的弟弟还小。", "My brother is still small."),
    (26, "bon", "adj", "A1", "好的", "good", "C'est un bon ami.", "他是个好朋友。", "He is a good friend."),
    (27, "mauvais", "adj", "A1", "坏的", "bad", "Le temps est mauvais aujourd'hui.", "今天天气不好。", "The weather is bad today."),
    (28, "nouveau", "adj", "A1", "新的", "new", "Voici mon nouveau téléphone.", "这是我的新手机。", "Here is my new phone."),
    (29, "vieux", "adj", "A1", "老的", "old", "C'est un vieux bâtiment.", "这是一栋老建筑。", "This is an old building."),
    (30, "beau", "adj", "A1", "美的", "beautiful", "Quel beau paysage !", "多美的风景啊！", "What a beautiful landscape!"),
    (31, "toujours", "adv", "A1", "总是", "always", "Il est toujours en retard.", "他总是迟到。", "He is always late."),
    (32, "souvent", "adv", "A1", "经常", "often", "Je vais souvent au cinéma.", "我经常去电影院。", "I often go to the cinema."),
    (33, "parfois", "adv", "A1", "有时", "sometimes", "Parfois, il oublie ses clés.", "有时候，他会忘记钥匙。", "Sometimes, he forgets his keys."),
    (34, "jamais", "adv", "A1", "从不", "never", "Je ne fume jamais.", "我从不吸烟。", "I never smoke."),
    (35, "ici", "adv", "A1", "这里", "here", "Viens ici.", "过来这里。", "Come here."),
    (36, "là", "adv", "A1", "那里", "there", "Regarde là-bas.", "看那边。", "Look over there."),
    (37, "maintenant", "adv", "A1", "现在", "now", "Que faisons-nous maintenant ?", "我们现在做什么？", "What are we doing now?"),
    (38, "aujourd'hui", "adv", "A1", "今天", "today", "Aujourd'hui, il fait beau.", "今天天气很好。", "Today, the weather is nice."),
    (39, "demain", "adv", "A1", "明天", "tomorrow", "À demain !", "明天见！", "See you tomorrow!"),
    (40, "hier", "adv", "A1", "昨天", "yesterday", "Hier, j'étais fatigué.", "昨天我很累。", "Yesterday, I was tired."),
    (41, "pourquoi", "adv", "A1", "为什么", "why", "Pourquoi tu pleures ?", "你为什么哭？", "Why are you crying?"),
    (42, "comment", "adv", "A1", "怎样", "how", "Comment tu t'appelles ?", "你叫什么名字？", "What is your name?"),
    (43, "quand", "adv", "A1", "什么时候", "when", "Quand pars-tu ?", "你什么时候走？", "When are you leaving?"),
    (44, "où", "adv", "A1", "哪里", "where", "Où habites-tu ?", "你住在哪里？", "Where do you live?"),
    (45, "qui", "pron", "A1", "谁", "who", "Qui est là ?", "谁在那儿？", "Who is there?"),
    (46, "que", "pron", "A1", "什么", "what", "Qu'est-ce que c'est ?", "这是什么？", "What is it?"),
    (47, "avec", "prep", "A1", "和...一起", "with", "Je dîne avec ma famille.", "我和家人一起吃晚餐。", "I dine with my family."),
    (48, "pour", "prep", "A1", "为了；给", "for", "C'est un cadeau pour toi.", "这是给你的礼物。", "This is a gift for you."),
    (49, "dans", "prep", "A1", "在...里", "in", "Le chat est dans la boîte.", "猫在盒子里。", "The cat is in the box."),
    (50, "sur", "prep", "A1", "在...上", "on", "Le livre est sur la table.", "书在桌子上。", "The book is on the table."),
    (51, "sous", "prep", "A1", "在...下", "under", "Le chien dort sous le lit.", "狗在床底下睡觉。", "The dog is sleeping under the bed."),
    (52, "devant", "prep", "A1", "在...前", "in front of", "Il y a une voiture devant la maison.", "房子前面有一辆车。", "There is a car in front of the house."),
    (53, "derrière", "prep", "A1", "在...后", "behind", "Cache-toi derrière l'arbre.", "躲在树后面。", "Hide behind the tree."),
    (54, "avant", "prep", "A1", "在...之前", "before", "Arrive avant midi.", "中午前到达。", "Arrive before noon."),
    (55, "après", "prep", "A1", "在...之后", "after", "Après la pluie, le beau temps.", "雨过天晴。", "After rain comes fair weather."),
    
    (56, "chemin", "nm", "A2", "路；道路", "path; way", "Quel est le meilleur chemin pour y aller ?", "去那里最好的路是哪条？", "What is the best way to get there?"),
    (57, "voyage", "nm", "A2", "旅行", "trip", "Bon voyage !", "旅途愉快！", "Have a good trip!"),
    (58, "vacances", "nf", "A2", "假期", "vacation", "Je pars en vacances.", "我去度假。", "I am going on vacation."),
    (59, "argent", "nm", "A2", "钱；银子", "money; silver", "Il n'a pas beaucoup d'argent.", "他没有很多钱。", "He doesn't have much money."),
    (60, "temps", "nm", "A2", "时间；天气", "time; weather", "Je n'ai pas le temps.", "我没有时间。", "I don't have time."),
    (61, "heure", "nf", "A2", "小时；时间", "hour; time", "Quelle heure est-il ?", "现在几点了？", "What time is it?"),
    (62, "jour", "nm", "A2", "天", "day", "Passez une bonne journée !", "祝你今天过得愉快！", "Have a nice day!"),
    (63, "semaine", "nf", "A2", "星期", "week", "Je travaille la semaine prochaine.", "我下周工作。", "I work next week."),
    (64, "mois", "nm", "A2", "月", "month", "Il partira le mois prochain.", "他下个月会离开。", "He will leave next month."),
    (65, "année", "nf", "A2", "年", "year", "Bonne année !", "新年快乐！", "Happy New Year!"),
    (66, "vie", "nf", "A2", "生活；生命", "life", "C'est la vie.", "这就是生活。", "That's life."),
    (67, "monde", "nm", "A2", "世界", "world", "Il a voyagé partout dans le monde.", "他在世界各地旅行过。", "He has traveled all over the world."),
    (68, "ville", "nf", "A2", "城市", "city", "Paris est une grande ville.", "巴黎是一个大城市。", "Paris is a big city."),
    (69, "pays", "nm", "A2", "国家", "country", "La France est un beau pays.", "法国是一个美丽的国家。", "France is a beautiful country."),
    (70, "rue", "nf", "A2", "街道", "street", "Ma maison est dans cette rue.", "我的房子在这条街上。", "My house is on this street."),
    (71, "voiture", "nf", "A2", "汽车", "car", "J'ai acheté une nouvelle voiture.", "我买了一辆新车。", "I bought a new car."),
    (72, "train", "nm", "A2", "火车", "train", "Le train arrive bientôt.", "火车快到了。", "The train is arriving soon."),
    (73, "avion", "nm", "A2", "飞机", "airplane", "Nous prenons l'avion demain.", "我们明天坐飞机。", "We are taking the plane tomorrow."),
    (74, "billet", "nm", "A2", "票", "ticket", "Avez-vous votre billet ?", "您有您的票吗？", "Do you have your ticket?"),
    (75, "chambre", "nf", "A2", "房间", "room", "Ma chambre est au premier étage.", "我的房间在一楼。", "My room is on the first floor."),
    (76, "lit", "nm", "A2", "床", "bed", "Ce lit est très confortable.", "这张床很舒服。", "This bed is very comfortable."),
    (77, "table", "nf", "A2", "桌子", "table", "Mettez les assiettes sur la table.", "把盘子放在桌子上。", "Put the plates on the table."),
    (78, "chaise", "nf", "A2", "椅子", "chair", "Veuillez vous asseoir sur cette chaise.", "请坐在这张椅子上。", "Please sit on this chair."),
    (79, "fenêtre", "nf", "A2", "窗户", "window", "Ferme la fenêtre, s'il te plaît.", "请把窗户关上。", "Close the window, please."),
    (80, "porte", "nf", "A2", "门", "door", "Ouvrez la porte !", "开门！", "Open the door!"),
    (81, "ordinateur", "nm", "A2", "电脑", "computer", "Il travaille sur son ordinateur.", "他在他的电脑上工作。", "He is working on his computer."),
    (82, "téléphone", "nm", "A2", "电话", "phone", "Mon téléphone sonne.", "我的电话在响。", "My phone is ringing."),
    (83, "télévision", "nf", "A2", "电视", "television", "Nous regardons la télévision le soir.", "我们在晚上看电视。", "We watch television in the evening."),
    (84, "film", "nm", "A2", "电影", "movie", "C'est un excellent film.", "这是一部出色的电影。", "It's an excellent movie."),
    (85, "musique", "nf", "A2", "音乐", "music", "J'écoute de la musique classique.", "我听古典音乐。", "I listen to classical music."),
    (86, "chanson", "nf", "A2", "歌曲", "song", "Elle chante une belle chanson.", "她在唱一首美丽的歌。", "She is singing a beautiful song."),
    (87, "livre", "nm", "A2", "书", "book", "Ce livre est très intéressant.", "这本书非常有趣。", "This book is very interesting."),
    (88, "mot", "nm", "A2", "词汇；单词", "word", "Je ne comprends pas ce mot.", "我不懂这个词。", "I don't understand this word."),
    (89, "lettre", "nf", "A2", "信；字母", "letter", "Il a écrit une lettre à sa mère.", "他给母亲写了一封信。", "He wrote a letter to his mother."),
    (90, "stylo", "nm", "A2", "钢笔", "pen", "Prête-moi ton stylo.", "把你的钢笔借给我。", "Lend me your pen."),
    (91, "cahier", "nm", "A2", "笔记本", "notebook", "Ouvrez vos cahiers.", "打开你们的笔记本。", "Open your notebooks."),
    (92, "professeur", "nm", "A2", "老师；教授", "teacher; professor", "Notre professeur est très strict.", "我们的老师非常严格。", "Our teacher is very strict."),
    (93, "étudiant", "nm", "A2", "大学生", "student", "C'est un étudiant brillant.", "他是一个聪明的学生。", "He is a brilliant student."),
    (94, "ami", "nm", "A2", "朋友", "friend", "C'est mon meilleur ami.", "他是我最好的朋友。", "He is my best friend."),
    (95, "famille", "nf", "A2", "家庭", "family", "J'aime beaucoup ma famille.", "我非常爱我的家庭。", "I love my family very much."),
    (96, "père", "nm", "A2", "父亲", "father", "Mon père est médecin.", "我的父亲是医生。", "My father is a doctor."),
    (97, "mère", "nf", "A2", "母亲", "mother", "Sa mère est gentille.", "他的母亲很亲切。", "His mother is kind."),
    (98, "frère", "nm", "A2", "兄弟", "brother", "Il a deux frères.", "他有两个兄弟。", "He has two brothers."),
    (99, "sœur", "nf", "A2", "姐妹", "sister", "Ma sœur est infirmière.", "我的妹妹是护士。", "My sister is a nurse."),
    (100, "enfant", "nm", "A2", "孩子", "child", "Les enfants jouent dehors.", "孩子们在外面玩。", "The children are playing outside."),

    (101, "décider", "v", "B1", "决定", "to decide", "Elle a décidé de partir.", "她决定离开。", "She decided to leave."),
    (102, "souvenir", "nm", "B1", "记忆；回忆", "memory; souvenir", "Ce souvenir me rend heureux.", "这个回忆让我开心。", "This memory makes me happy."),
    (103, "essayer", "v", "B1", "尝试", "to try", "J'essaie d'apprendre le français.", "我尝试学法语。", "I try to learn French."),
    (104, "entier", "adj", "B1", "整个的", "whole; entire", "Il a lu le livre entier.", "他读完了整本书。", "He read the entire book."),
    (105, "raison", "nf", "B1", "理由；道理", "reason", "Tu as raison !", "你是对的！", "You are right!"),
    (106, "ensuite", "adv", "B1", "然后；接下来", "then; next", "D'abord on mange, ensuite on dort.", "先吃饭，然后睡觉。", "First we eat, then we sleep."),
    (107, "plusieurs", "adj", "B1", "好几个；几个", "several; multiple", "Plusieurs personnes sont venues.", "好几个人来了。", "Several people came."),
    (108, "surtout", "adv", "B1", "尤其；特别", "especially; above all", "J'aime le chocolat, surtout le noir.", "我喜欢巧克力，尤其是黑巧克力。", "I like chocolate, especially dark."),
    (109, "comprendre", "v", "B1", "理解；明白", "to understand", "Je ne comprends pas cette phrase.", "我不理解这句话。", "I don't understand this sentence."),
    (110, "apprendre", "v", "B1", "学习", "to learn", "Il apprend le français depuis un an.", "他学法语一年了。", "He has been learning French for a year."),
    (111, "connaître", "v", "B1", "认识；了解", "to know (somebody)", "Je connais bien cette ville.", "我很了解这个城市。", "I know this city well."),
    (112, "savoir", "v", "B1", "知道", "to know (a fact)", "Sais-tu où il est ?", "你知道他在哪里吗？", "Do you know where he is?"),
    (113, "croire", "v", "B1", "相信；认为", "to believe", "Je crois qu'il a raison.", "我认为他是对的。", "I believe he is right."),
    (114, "penser", "v", "B1", "想；认为", "to think", "Qu'en penses-tu ?", "你怎么看？", "What do you think about it?"),
    (115, "trouver", "v", "B1", "找到；觉得", "to find", "Je trouve cette idée géniale.", "我觉得这个主意棒极了。", "I find this idea brilliant."),
    (116, "chercher", "v", "B1", "寻找", "to look for", "Je cherche mes clés.", "我在找我的钥匙。", "I am looking for my keys."),
    (117, "donner", "v", "B1", "给", "to give", "Il m'a donné un cadeau.", "他给了我一个礼物。", "He gave me a gift."),
    (118, "prendre", "v", "B1", "拿；乘坐；吃", "to take", "Je prends le bus.", "我坐公交车。", "I take the bus."),
    (119, "mettre", "v", "B1", "放；穿", "to put", "Mets ton manteau.", "穿上你的外套。", "Put on your coat."),
    (120, "laisser", "v", "B1", "留下；让", "to leave; to let", "Laisse-moi tranquille.", "让我一个人静一静。", "Leave me alone."),
    (121, "attendre", "v", "B1", "等待", "to wait", "J'attends le train.", "我在等火车。", "I am waiting for the train."),
    (122, "entendre", "v", "B1", "听见", "to hear", "Je n'entends rien.", "我什么也听不见。", "I don't hear anything."),
    (123, "répondre", "v", "B1", "回答", "to answer", "Répondez à ma question.", "回答我的问题。", "Answer my question."),
    (124, "demander", "v", "B1", "问；要求", "to ask", "Il demande son chemin.", "他在问路。", "He is asking for directions."),
    (125, "expliquer", "v", "B1", "解释", "to explain", "Peux-tu m'expliquer cela ?", "你能给我解释一下这个吗？", "Can you explain this to me?"),
    (126, "commencer", "v", "B1", "开始", "to begin; to start", "Le cours commence à huit heures.", "课程八点开始。", "The class starts at eight o'clock."),
    (127, "finir", "v", "B1", "结束", "to finish", "J'ai fini mon travail.", "我完成了我的工作。", "I finished my work."),
    (128, "choisir", "v", "B1", "选择", "to choose", "Choisis un livre.", "选一本书。", "Choose a book."),
    (129, "réussir", "v", "B1", "成功", "to succeed", "Il a réussi son examen.", "他考试及格了。", "He passed his exam."),
    (130, "perdre", "v", "B1", "失去；输", "to lose", "J'ai perdu mon portefeuille.", "我丢了我的钱包。", "I lost my wallet."),
    (131, "gagner", "v", "B1", "赢；赚", "to win; to earn", "Notre équipe a gagné le match.", "我们的队伍赢得了比赛。", "Our team won the match."),
    (132, "acheter", "v", "B1", "买", "to buy", "J'achète des légumes.", "我买蔬菜。", "I buy vegetables."),
    (133, "vendre", "v", "B1", "卖", "to sell", "Ils vendent leur maison.", "他们在卖他们的房子。", "They are selling their house."),
    (134, "payer", "v", "B1", "支付", "to pay", "Je vais payer l'addition.", "我要付账。", "I will pay the bill."),
    (135, "porter", "v", "B1", "穿戴；携带", "to wear; to carry", "Elle porte une belle robe.", "她穿着一件漂亮的裙子。", "She is wearing a beautiful dress."),

    (136, "atteindre", "v", "B2", "达到；抵达", "to reach; to achieve", "Il a atteint son objectif.", "他达到了目标。", "He achieved his goal."),
    (137, "cependant", "adv", "B2", "然而；但是", "however; nevertheless", "Cependant, il fait froid.", "然而，天气很冷。", "However, it is cold."),
    (138, "développement", "nm", "B2", "发展", "development", "Le développement économique est rapide.", "经济发展很快。", "Economic development is rapid."),
    (139, "évidemment", "adv", "B2", "显然；明显地", "obviously; evidently", "Évidemment, il a raison.", "显然，他是对的。", "Obviously, he is right."),
    (140, "fournir", "v", "B2", "提供；供应", "to provide; to supply", "Ils fournissent des services.", "他们提供服务。", "They provide services."),
    (141, "maintenir", "v", "B2", "维持；保持", "to maintain; to keep", "Il faut maintenir la santé.", "必须保持健康。", "One must maintain health."),
    (142, "particulier", "adj", "B2", "特别的；特定的", "particular; specific", "Dans ce cas particulier...", "在这个特别的情况下...", "In this particular case..."),
    (143, "soutenir", "v", "B2", "支持；支撑", "to support; to sustain", "Ses amis le soutiennent.", "他的朋友们支持他。", "His friends support him."),
    (144, "probablement", "adv", "B2", "可能；大概", "probably; likely", "Il viendra probablement demain.", "他可能明天来。", "He will probably come tomorrow."),
    (145, "rencontrer", "v", "B2", "遇见；碰面", "to meet; to encounter", "J'ai rencontré un vieil ami.", "我遇到了一位老朋友。", "I met an old friend."),
    (146, "bien que", "conj", "B2", "虽然；尽管", "although; even though", "Bien qu'il pleuve, je sors.", "虽然在下雨，我还是出门。", "Although it rains, I go out."),
    (147, "améliorer", "v", "B2", "改善", "to improve", "Nous devons améliorer nos compétences.", "我们必须提高我们的技能。", "We must improve our skills."),
    (148, "découvrir", "v", "B2", "发现", "to discover", "Ils ont découvert un nouveau traitement.", "他们发现了一种新疗法。", "They discovered a new treatment."),
    (149, "partager", "v", "B2", "分享", "to share", "J'aimerais partager cette expérience.", "我想分享这个经验。", "I would like to share this experience."),
    (150, "exiger", "v", "B2", "要求", "to demand; to require", "Cette tâche exige de la patience.", "这项任务需要耐心。", "This task requires patience."),
]

def generate_csv(filepath):
    # Ensure directory exists
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    
    with open(filepath, 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(["id", "lemma", "pos", "level", "zh_meaning", "en_meaning", "example_fr", "example_zh", "example_en"])
        for row in words_data:
            writer.writerow(row)
    print(f"Generated {len(words_data)} words into {filepath}")

if __name__ == "__main__":
    generate_csv(os.path.join("data", "lexicon.csv"))
    # Overwrite sample as well to ensure fallback compatibility if the app still references it anywhere
    generate_csv(os.path.join("data", "lexicon_sample.csv"))
